name: ygg-torrent-mcp

services:
  ygg-torrent-mcp:
    container_name: ygg-torrent-mcp
    build: .
    image: ygg-torrent-mcp
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - YGG_PASSKEY=${YGG_PASSKEY}
    dns:
      - 9.9.9.9
      - 149.112.112.112
      - 2620:fe::fe
      - 2620:fe::9
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
